### ISSUE TITLE
Support JCorBX Model

### ISSUE THREAD

**Issue by terminet85** [weachy/CoreBookX-14-Hackintosh#22] opened 2022-01-19 07:30 UTC
I got a new CoreBookX with a new green motherboard.
As stated in the Readme, this EFI OpenCore set doesn't work.

Anyway would be I guess useful add support for this version too. And having one, I can contribute in order to achieve this goal.

So using this EFI OpenCore, when I boot to installer I got this error:

```
No argument are initialized for method [FCPU]

ACPI Error: Method parse/execution failed [\LIDP.FCPU] (Node ffffff937a22a5a8 RE_NOT_FOUND (28160938/psparse-632)
ACPI Error: [\_SB_.PC18.LPC.H_EC.ADP1._PSR] Namespace lookup failure, RE_NOT_FOUND (28160938/psargs-463)
[FCPU] @00093 #882D:

Initialized Local Variables for method [FCPU]:
     Local0: ffffff9379f86500 <Obj>         Integer: 0000000000000001
```

Any advice for what should do I look in order to fix first this error?
I'll share any fix that I could make!

Thank you so much

**Comment by weachy** [comment] 2022-01-19 18:30
It's almost a new model notebook, except for the same look, CPU, and screen, because too much much difference inside. So I suggest you to treat it as a new model and create a new repository to discuss.

**Comment by terminet85** [comment] 2022-01-20 07:35
> It's almost a new model notebook, except for the same look, CPU, and screen, because too much much difference inside. So I suggest you to treat it as a new model and create a new repository to discuss.

Okay I'll do that, but alone I cannot do much. 
First to fork your repo, could you help me, with documents and how-to in order to fix the issues?

**Comment by weachy** [comment] 2022-01-23 06:25
Duplicate of #21

**Closed by weachy** 2022-01-23 06:25 UTC

**Comment by Anycubic** [comment] 2022-01-26 18:03
Hello, just bought a JCorBX model as well. Unfortunately this was supposed to be my first OpenCore attempt so I can only help by testing. Audio chip seems the same as old model (Realtek), so maybe it is fixable, don't know about battery.

**Comment by Anycubic** [comment] 2022-01-26 20:46
>  No audio
> 

@terminet85  I see now audio is ALC269 and not ALC897, so this could be the problem

**Comment by terminet85** [comment] 2022-01-27 05:17
@Anycubic hello!
Thread is closed by dev. It’s impolite keeping writing. It’s clear that he wouldn’t give any help.

I’m working for a fix here https://github.com/rboldini/CoreBook_X_OC/issues/11 please move there ;)

**Comment by Anycubic** [comment] 2022-01-27 08:02
@terminet85 hello I'm sorry, I've notice it was closed after I replied, I'll collaborate with you! I'll move to the one you mentioned 😉
